airports/urls.py
# Load path from django.urls
from django.urls import path
# Load this application's views.py file
from . import views

# Define url patterns
urlpatterns = [
    # Get index view
    # Example url: /airports/
    path('', views.index),
    # Show Airport info
    # Example url /airports/MYR
    # Notice: the airport_code parameter in the url matches
    #   the parameter in the airport_info function

    path('<str:airport_code>', views.airport_info),




]

csci409/urls.py
from django.contrib import admin
from django.urls import include, path

import airports.views
import flights.views
import routes.views
import tickets.views

urlpatterns = [
    path('', airports.views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('airports/', include('airports.urls')),
    path('flights/', include('flights.urls')),
    path('routes/', include('routes.urls')),
    path('tickets/', include('tickets.urls')),
]

flights/urls.py
from django.urls import path
from . import views

urlpatterns = [


    path('', views.index),

    # path('/search/<str:origin>/<str:destination>', views.flight_search)

    path('search/', views.search),
]

routes/urls.py
from django.urls import path
from . import views

urlpatterns = [


    path('', views.index),

    path('search/<str:origin>/<str:destination>', views.route_search)

]

tickets/urls.py
from django.urls import path
from. import views

urlpatterns = [

    path('', views.index),

    # path('/<int:confirmation_number>', views.ticket_search),

    path('search/', views.search),


]

airports/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    name = models.CharField(max_length=255)
    airport_code = models.CharField(max_length=3)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5)
    is_open = models.BooleanField()

class Runway(models.Model):
    LEFT = 'L'
    CENTER = 'C'
    RIGHT = 'R'
    NONE = 'N'
    RUNWAY_DESIGNATION_CHOICES = [
        (LEFT, 'Left'),
        (CENTER, 'Center'),
        (RIGHT, 'Right'),
        (NONE, 'None'),
    ]
    runway_number = models.IntegerField()
    runway_designation = models.CharField(
        max_length=1,
        choices=RUNWAY_DESIGNATION_CHOICES,
        default=NONE
    )
    length = models.IntegerField()
    width = models.IntegerField()
    airport = models.ForeignKey(Airport, on_delete=models.CASCADE)

flights/models.py
from django.db import models
from airports.models import Airport
# Create your models here.

class Airline(models.Model):
    airline_name = models.CharField(max_length=30)
    airline_code = models.CharField(max_length=2)

    def __str__(self):
        return self.airline_code



class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.PROTECT, related_name='flight_origin')
    destination = models.ForeignKey(Airport, on_delete=models.PROTECT, related_name='flight_destination')
    departure = models.DateTimeField()
    arrival = models.DateTimeField()
    aircraft_type = models.CharField(max_length=10)
    airline = models.ForeignKey(Airline, on_delete=models.PROTECT, related_name='flight_airline')
    flight_number = models.IntegerField()

    def __str__(self):
        return self.airline.airline_code + str(self.flight_number)

routes/models.py
from django.db import models

# Create your models here.

tickets/models.py
from django.db import models
from flights.models import Flight
# Create your models here.
class Reservation(models.Model):
    flight = models.ForeignKey(Flight, on_delete=models.PROTECT)
    num_people = models.IntegerField()
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)

class Ticket(models.Model):
    FIRST = 'F'
    BUSINESS = 'B'
    MAIN = 'M'
    TICKET_OPTIONS = [
        (FIRST, 'First Class'),
        (BUSINESS, 'Business Class'),
        (MAIN, 'Main Cabin'),
    ]
    reservation = models.ForeignKey(Reservation, on_delete=models.PROTECT)
    seat = models.CharField(max_length=10)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    ticket_class = models.CharField(
        max_length=1,
        choices=TICKET_OPTIONS,
        default=MAIN
    )

flights/forms.py
from django import forms

class FlightSearch(forms.Form):
    origin = forms.CharField(label='Origin Airport')
    destination = forms.CharField(label='Destination Airport')

tickets/forms.py
from django import forms

class TicketForm(forms.Form):
    confirmation_number = forms.IntegerField(label='Confirmation Number')

airports/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Airport

def index(request):
    airports = Airport.objects.all()  # gather data from the database
    context = {'airports': airports}  # assign it to a context variable
    return render(request, 'airports/index.html', context)  # render the template with the context data
def airport_info(request, airport_code):
    airport = Airport.objects.get(airport_code=airport_code)  # gather the data matching the necessary parameters
    context = {'airport': airport}  # attach line 10's result to a context variable
    return render(request, 'airports/airport.html', context)  # render the template using the context variable

flights/views.py
# from django.http import HttpResponse
from django.shortcuts import render
from .forms import FlightSearch
from .models import Flight
# Import Flight model
from airports.models import Airport
# Import airport model to get airport id and code

 # def index(request):
    # Fetch all flights
    #  flights = Flight.objects.all()
    #  flight_list = ', '.join([f.origin.airport_code + "->" + f.destination.airport_code for f in flights])
    #  return HttpResponse('Listing all flights: ' + flight_list)

# def flight_search(request, origin, destination):
    # origin = Airport.objects.get(airport_code=origin)
    # destination = Airport.objects.get(airport_code=destination)
    # Code to select flights from the database
    # flights = Flight.objects.filter(origin_id=origin).filter(destination_id=destination)
    # flight_list = ', '.join([f.origin.airport_code + "->" + f.destination.airport_code + " Airline Code: " + f.airline.airline_code for f in flights])
    # return HttpResponse('Showing flights: ' + flight_list)

def index(request):
    # create an instance of the form class
    form = FlightSearch()
    # render the form
    return render(request, 'flights/index.html', {'form': form})

def search(request):
    form = FlightSearch(request.POST)
    if form.is_valid():
        flights = Flight.objects.filter(origin__airport_code=form.cleaned_data['origin']).filter(destination__airport_code=form.cleaned_data['destination'])
        return render(request, 'flights/flight_search.html', {'flights': flights})


# def index(request):
   # return HttpResponse("Hello from flights")

#def flight_search(request, origin, destination):
   # return HttpResponse("Showing flights from " + origin + " to " + destination + ".")

routes/admin.py
from django.contrib import admin

# Register your models here.

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'

routes/tests.py
from django.test import TestCase

# Create your tests here.

routes/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello from routes")

def route_search(request, origin, destination):
    return HttpResponse("Showing routes from " + origin + " to " + destination + ".")

tickets/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from .models import Reservation
from .forms import TicketForm


@login_required()
def index(request):
    # Create an instance of the form class
    form = TicketForm()
    # render the form
    return render(request, 'tickets/index.html', {'form': form})

def search(request):
    form = TicketForm(request.POST)
    if form.is_valid():
        reservation = Reservation.objects.get(id=form.cleaned_data['confirmation_number'])
        return render(request, 'tickets/ticket_search.html', {'reservation': reservation})


# def ticket_search(request, confirmation_number):
    # Select the singular reservation for the confirmation number
    # Note: the confirmation_number is the id in the Reservation table
    # reservation = Reservation.objects.get(id=confirmation_number)
    # return HttpResponse(
       # 'Number of tickets for confirmation number: ' + str(confirmation_number) + " is " + str(reservation.num_people))

airports/templates/airports/airport.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<!-- Q1. Inside the h1 tag display the airport_code- airport name -->
<h1>{{airport.airport_code}}- {{airport.name}}</h1>
<!-- Display the airport address -->
<h2>Address</h2>
<p>{{airport.address}} {{airport.city}}, {{airport.state}} {{airport.zipcode}}</p>
<h2>Runways</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Runway</th>
            <th scope="col">Length</th>
            <th scope="col">Width</th>
        </tr>
    </thead>
    <tbody>
        <!-- Q3 Display the runway number along with designation L,C,R, etc. -->
        <!-- Runway length and width  in a table row-->
        {% for runway in airport.runway_set.all %} <!-- this is a new type of object it will fetch all of the associated runways -->
            <tr>
                <td>{{runway.runway_number}}{{runway.runway_designation}}</td>
                <td>{{runway.length}}</td>
                <td>{{runway.width}}</td>

            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

airports/templates/airports/index.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<h1>Airports</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Airport Code</th>
            <th scope="col">Airport Name</th>
            <th scope="col">More Information</th>
        </tr>
    </thead>
    <tbody>
        {% for airport in airports %} <!-- Loop through airports from the context variable specified in views.py -->
            <tr>
                <td>{{ airport.airport_code }}</td>
                <td>{{ airport.name }}</td>
                <td><a href="/airports/{{ airport.airport_code }}">More Information</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

flights/templates/flights/flight_search.html
{% extends 'base.html' %}

{% block content %}
<h1>Showing Flights</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Origin Airport</th>
            <th scope="col">Destination Airport</th>
            <th scope="col">Flight</th>
            <th scope="col">Departure</th>
            <th scope="col">Arrival</th>
        </tr>
    </thead>

    <tbody>
        {% for flight in flights %}
            <tr>
                <td>{{ flight.origin.airport_code }}</td>
                <td>{{ flight.destination.airport_code }}</td>
                <td>{{ flight.airline }}{{ flight.flight_number }}</td>
                <td>{{ flight.departure }}</td>
                <td>{{ flight.arrival }}</td>
            </tr>
        {% endfor %}




    </tbody>



</table>
{%endblock%}

flights/templates/flights/index.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<form action="/flights/search/" method="post">
    <!-- Create a csrf token -->
    {% csrf_token %}
    <!-- Output the form -->
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">CSCI 409</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/airports">Airports</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/flights">Flights</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/tickets">Tickets</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-item" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<main>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
</body>
</html>

tickets/templates/tickets/index.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<form action="/tickets/search/" method="post">
    <!-- Create a csrf token -->
    {% csrf_token %}
    <!-- Output the form -->
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

tickets/templates/tickets/ticket_search.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<h1>Confirmation Number- {{ reservation.id }}</h1>
<table class="table">
    <tr>
        <td><strong>Number of People</strong></td>
        <td>{{ reservation.num_people }}</td>
    </tr>
    <tr>
        <td><strong>Total Cost</strong></td>
        <td>{{ reservation.total_cost }}</td>
    </tr>
</table>
<!-- 5 Extra Credit Points  Create a table that displays the flight information -->
<!-- This should display the airline, flight number, arrival and departure airports, and arrival and departure times -->


<!-- 5 Extra Credit Points Create a table that displays the ticket information -->
{% endblock %}